"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ek43e(9%t9$fq*cy8hzku&x3fn+l#nwo)_c406ub6^)h8d81o2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


#CSRF TRUSTED ORIGINS
CSRF_TRUSTED_ORIGINS = ['https://giglance.info']


# Application definition

CRISPY_TEMPLATE_PACK = 'bootstrap3'

INSTALLED_APPS = [
    # django apps
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # local apps
    'apps.users.apps.UsersConfig',
    'apps.courses.apps.CoursesConfig',

    #User Registration
    'crispy_forms',
    # 'apps.recom.apps.recomConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)



AUTH_USER_MODEL = 'users.CustomUser'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL ='home'

# STRIPE_PUBLISHABLE_KEY = 'pk_test_51NecLpCn3yES92jnHG1cy8bybsTsOVd7JiKRyyqABh2gC1FSowwDEIjFT6Gxn7bqfFrNHgnIFJA2EojtiWgqo7Sv00EA1O5EvN'
# STRIPE_SECRET_KEY = 'sk_test_51NecLpCn3yES92jn7hNnZlKpT1BLOLKSmtnDm7TJCx5JIUjfgKO8iiqjON44oxSeCfQztziHMYPXApKAl0FbKGId00WuPEFAaw'
# STRIPE_CONNECT_CLIENT_ID = 'ca_ORViS8Vevrp4p9JHNfq0lhd7nRLnANS1'


BACKEND_DOMAIN = ("http://127.0.0.1:8000")
PAYMENT_SUCCESS_URL = ("http://127.0.0.1:8000/")
PAYMENT_CANCEL_URL = ("http://127.0.0.1:8000/about-us/")

# BACKEND_DOMAIN=http://127.0.0.1:8000
# PAYMENT_SUCCESS_URL=http://127.0.0.1:8000/success/
# PAYMENT_CANCEL_URL=http://127.0.0.1:8000/cancel/

STRIPE_PUBLISHABLE_KEY = 'pk_live_FDQsn5JRkGO1jypUNNiwFtbz00jTLkQ0bB'
STRIPE_SECRET_KEY = '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'
STRIPE_CONNECT_CLIENT_ID = 'ca_OJGDTLUbxGXZjxM8KtmD3BBw5jNlBOrY'


stripe_Account_Modify = [
    {'Connected_Acc': 'STRIPE_CONNECT_CLIENT_ID',
     'Account_ID': 'STRIPE_PUBLISHABLE_KEY',
     'Account_Secret': 'STRIPE_SECRET_KEY'
     
},
{
    'interval': '2',
    'manual': 'true',
    'schedule': 'interval ; manual',
    'payouts': 'schedule',
}
]


