# Generated by Django 4.2 on 2023-11-24 08:50

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('Software Development & IT Services', 'Renewable Energy')], default='Software Development & IT Services', max_length=50)),
                ('location', models.CharField(default='San Francisco, California, USA', max_length=255)),
                ('founded', models.DateField(default=2007)),
                ('employees', models.CharField(default='500-1000', max_length=20)),
                ('ceo', models.CharField(default='Jane Smith', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=200, null=True, populate_from='title', unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fee', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Enter the job role', max_length=100)),
                ('job_description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('requirements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the meeting title', max_length=100)),
                ('attendees', models.TextField()),
                ('agenda', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project_Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the project title', max_length=255)),
                ('introduction', models.TextField()),
                ('project_overview', models.TextField()),
                ('technologies_in_use', models.TextField()),
                ('project_scope_in_scope', models.TextField()),
                ('project_scope_out_of_scope', models.TextField()),
                ('stakeholders', models.TextField()),
                ('project_timeline', models.TextField()),
                ('project_deliverables', models.TextField()),
                ('risk_management', models.TextField()),
                ('conclusion', models.TextField()),
                ('appendices', models.TextField()),
            ],
        ),
    ]
