# Generated by Django 4.2 on 2023-11-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_documentation',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
        migrations.AddField(
            model_name='job_description',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
        migrations.AddField(
            model_name='course',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
        migrations.AddField(
            model_name='company_profile',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
    ]
